name: sized_context_example
description: A new Flutter application.
version: 1.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  universal_platform:
    path: ../

flutter:
  uses-material-design: true

publish_to: none
